export const UPDATE_EDIT_STATE = 'UPDATE_EDIT_STATE';
export const CHANGE_TITLE_REQUEST = 'CHANGE_TITLE_REQUEST';
export const CHANGE_TITLE_FAILURE = 'CHANGE_TITLE_FAILURE';
export const CHANGE_TITLE_SUCCESS = 'CHANGE_TITLE_SUCCESS';
export const CANCEL_TITLE_CHANGE = 'CANCEL_TITLE_CHANGE';
export const FETCH_CONTENT_REQUEST = 'FETCH_CONTENT_REQUEST';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILURE = 'FETCH_CONTENT_FAILURE';
